version: "3.7"
services:
    # imagem micro 01
    api:
        build: 
            args: 
                user: luanramos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - apinetwork
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8000:80
            - 443:443
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - apinetwork

    # mysql micro 01
    db_api:
        image: arm64v8/mysql:oracle
        restart: unless-stopped
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes: 
            - /var/lib/mysql
        ports: 
            - 3308:3306
        networks: 
            - apinetwork

    #redis
    redis:
        image: redis:latest
        networks: 
            - apinetwork

networks: 
    apinetwork:
        driver: bridge